version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: ph_database
    environment:
      MYSQL_DATABASE: ph_database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./migrations/create_initial_tables.sql:/docker-entrypoint-initdb.d/create_initial_tables.sql
  phpmyadmin:
    image: phpmyadmin
    container_name: ph_phpmyamdmin
    restart: always
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      PMA_HOST: database